data:
  site:
    title: "Vishwaprakriti Ayurveda"

  carousel:
    - title: "Rediscover Ancient Healing"
      subtitle: "Nature’s wisdom blended in every drop."
      image: "icons/pslide1.jpg"

    - title: "Rooted in Nature"
      subtitle: "Healing begins when nature meets your routine."
      image: "icons/pslide2.jpg"

    - title: "Wellness, The Natural Way"
      subtitle: "Experience modern living with age-old Ayurvedic balance."
      image: "icons/pslide3.jpg"

  products:
    - title: "Nityam Suvarnaprashan – Ayurvedic Immunity Booster for Test"
      description: "A powerful Ayurvedic formulation specially crafted for children, Nityam Suvarnaprashan strengthens immunity, sharpens memory, and supports holistic development. Made with Suvarna Bhasma and other time-tested herbs, this formulation is rooted in ancient wisdom and backed by modern science"
      features:
        - "Boosts immunity"
        - "Improves memory"
        - "Supports digestive health"
        - "Safe, natural & chemical-free"
        - "Boosts immunity"

      button_text: "Order Now"
      image: "/icons/product1.jpg"
    - title: "Gajanan"
      description: "A powerful Ayurvedic formulation specially crafted for children, Nityam Suvarnaprashan strengthens immunity, sharpens memory, and supports holistic development. Made with Suvarna Bhasma and other time-tested herbs, this formulation is rooted in ancient wisdom and backed by modern science"
      features:
        - "Boosts immunity"
        - "Improves memory"
        - "Supports digestive health"
        - "Safe, natural & chemical-free"
        - "Boosts immunity"

      button_text: "Order Now"
      image: "/icons/productG.jpg"

    - title: "Nityam Suvarnaprashan – Ayurvedic Immunity Booster for Kids"
      description: "A powerful Ayurvedic formulation specially crafted for children, Nityam Suvarnaprashan strengthens immunity, sharpens memory, and supports holistic development. Made with Suvarna Bhasma and other time-tested herbs, this formulation is rooted in ancient wisdom and backed by modern science"
      features:
        - "Boosts immunity"
        - "Improves memory"
        - "Supports digestive health"
        - "Safe, natural & chemical-free"
        - "Boosts immunity"

      button_text: "Order Now"
      image: "/icons/product2.jpg"

    - title: "Nityam Suvarnaprashan – Ayurvedic Immunity Booster for Kids"
      description: "A powerful Ayurvedic formulation specially crafted for children, Nityam Suvarnaprashan strengthens immunity, sharpens memory, and supports holistic development. Made with Suvarna Bhasma and other time-tested herbs, this formulation is rooted in ancient wisdom and backed by modern science"
      features:
        - "Boosts immunity"
        - "Improves memory"
        - "Supports digestive health"
        - "Safe, natural & chemical-free"
        - "Boosts immunity"

      button_text: "Order Now"
      image: "/icons/product1.jpg"

    - title: "Nityam Suvarnaprashan – Ayurvedic Immunity Booster for Kids"
      description: "A powerful Ayurvedic formulation specially crafted for children, Nityam Suvarnaprashan strengthens immunity, sharpens memory, and supports holistic development. Made with Suvarna Bhasma and other time-tested herbs, this formulation is rooted in ancient wisdom and backed by modern science"
      features:
        - "Boosts immunity"
        - "Improves memory"
        - "Supports digestive health"
        - "Safe, natural & chemical-free"
        - "Boosts immunity"

      button_text: "Order Now"
      image: "/icons/product2.jpg"

    - title: "Nityam Suvarnaprashan – Ayurvedic Immunity Booster for Kids"
      description: "A powerful Ayurvedic formulation specially crafted for children, Nityam Suvarnaprashan strengthens immunity, sharpens memory, and supports holistic development. Made with Suvarna Bhasma and other time-tested herbs, this formulation is rooted in ancient wisdom and backed by modern science"
      features:
        - "Boosts immunity"
        - "Improves memory"
        - "Supports digestive health"
        - "Safe, natural & chemical-free"
        - "Boosts immunity"

      button_text: "Order Now"
      image: "/icons/product3.jpg"

    - title: "Nityam Suvarnaprashan – Ayurvedic Immunity Booster for Kids"
      description: "A powerful Ayurvedic formulation specially crafted for children, Nityam Suvarnaprashan strengthens immunity, sharpens memory, and supports holistic development. Made with Suvarna Bhasma and other time-tested herbs, this formulation is rooted in ancient wisdom and backed by modern science"
      features:
        - "Boosts immunity"
        - "Improves memory"
        - "Supports digestive health"
        - "Safe, natural & chemical-free"
        - "Boosts immunity"

      button_text: "Order Now"
      image: "/icons/product4.jpg"

  footer:
    text: "© 2026 Vishwaprakriti Ayurveda"
